### ISSUE TITLE
hi，please provide your data in this paper,thanks

### ISSUE THREAD

**Issue by twythebest** [Yanci87/LR-XFL-Logical-Reasoning-based-Explainable-Federated-Learning#1]
hi，please provide your data in this paper,thanks

**Comment by Yanci87** [comment]
Hi,

You can find the MIMIC dataset via https://archive.physionet.org/mimic2/, the VDem dataset via https://www.v-dem.net/data/dataset-archive/country-year-v-dem-fullothers-v11/, the MNIST dataset via https://yann.lecun.com/exdb/mnist/, and the CUB dataset via https://www.vision.caltech.edu/datasets/cub_200_2011/. The preprocess for MNIST and CUB follows https://github.com/pietrobarbiero/logic_explained_networks/tree/Experments?tab=readme-ov-file

**Comment by twythebest** [comment]
and please inform me that what version your&nbsp;pytorch_lightning is?thanks!




twy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yanci87/LR-XFL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月12日(星期一) 下午4:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yanci87/LR-XFL] hi，please provide your data in this paper,thanks (Issue #1)





 
Hi,
 
You can find the MIMIC dataset via https://archive.physionet.org/mimic2/, the VDem dataset via https://www.v-dem.net/data/dataset-archive/country-year-v-dem-fullothers-v11/, the MNIST dataset via https://yann.lecun.com/exdb/mnist/, and the CUB dataset via https://www.vision.caltech.edu/datasets/cub_200_2011/. The preprocess for MNIST and CUB follows https://github.com/pietrobarbiero/logic_explained_networks/tree/Experments?tab=readme-ov-file

**Comment by Yanci87** [comment]
The pytorch-lightning version is 1.7.7

**Comment by twythebest** [comment]
sorry for asking that:what your torch and pytorch version is?




twy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yanci87/LR-XFL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月12日(星期一) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yanci87/LR-XFL] hi，please provide your data in this paper,thanks (Issue #1)





 
The pytorch-lightning version is 1.7.7

**Comment by twythebest** [comment]
sorry for bothering you:I am a student ,and I cannot have the acess to MIMIC dataset ,please provide me with that, I promised to use it just for learning FL,I will be very grateful if you can give me this dataset,thanks!




twy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yanci87/LR-XFL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月12日(星期一) 下午4:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yanci87/LR-XFL] hi，please provide your data in this paper,thanks (Issue #1)





 
Hi,
 
You can find the MIMIC dataset via https://archive.physionet.org/mimic2/, the VDem dataset via https://www.v-dem.net/data/dataset-archive/country-year-v-dem-fullothers-v11/, the MNIST dataset via https://yann.lecun.com/exdb/mnist/, and the CUB dataset via https://www.vision.caltech.edu/datasets/cub_200_2011/. The preprocess for MNIST and CUB follows https://github.com/pietrobarbiero/logic_explained_networks/tree/Experments?tab=readme-ov-file
